language: php

php:
  - '7.0'

before_script:
  - composer config --global github-protocols https
  - composer global require "fxp/composer-asset-plugin"
  - composer config github-protocols https
  - composer install -vvv --no-interaction --prefer-dist

script: 'phpunit --bootstrap vendor/autoload.php tests'