language: php

php:
  - '7.0'

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer config github-oauth.github.com ${GH_TOKEN}
  - composer global require "fxp/composer-asset-plugin"
  - composer install --no-interaction --prefer-dist

script: 'phpunit --bootstrap vendor/autoload.php tests'